version: '3.8'

services:
  item-database:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: item-service-base
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: