server:
  port: 8060

openapi:
  id: ${API_ID:item-service}
  title: ${API_TITLE:Item service}
  description: ${API_DESCRIPTION:item-service description}

spring:
  application:
    name: ITEM-SERVICE

  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/item-service-base?authSource=admin&authMechanism=SCRAM-SHA-1